openapi: 3.0.0
info:
  title: NeuraMind AI API
  description: API documentation for the NeuraMind AI backend.
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local development server
paths:
  /:
    get:
      summary: Home endpoint
      description: Returns a welcome message.
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
  /route:
    get:
      summary: Route calculation
      description: Calculates a route between two locations.
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
  /generate-image:
    get:
      summary: Image generation
      description: Generates an image based on a prompt.
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
